# Numpy Implementation

In [9]:
import numpy as np
# Create a 2D Numpy array of size 1x3 with elements of your choice
arr1=np.ones((1,3))

# Create a Numpy array of length 50 with zeroes as its elements
arr2=np.zeros((50))

#Create a Numpy array of length 3x2 with elements of your choice
arr3=np.random.randint(1,10,size=(3,2))

arr4=np.dot(arr1,arr3)
print(arr4)

#Change 5th element of arr2 to a different number
arr2[4]=2
print(arr2)

if np.shape(arr4)==(1,2) and arr2[4]!=0:
  print("Passed")
else:
  print("Fail")

[[18. 13.]]
[0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
Passed


In [2]:
import numpy as np

#Task: Perform the dot product of I and 9I+1 using numpy, here I is referred to as an 3x3 Identity matrix.
I=np.identity(3)
unit=np.ones((3,3))
a=9*I + unit
final=np.dot(a,I)
print(final)


[[10.  1.  1.]
 [ 1. 10.  1.]
 [ 1.  1. 10.]]


# Pandas Implementation

In [3]:
import pandas as pd
import numpy as np

## Create a DataFrame from a dictionary
data = {
    'Name': ['Ramesh', 'Mahesh', 'Suresh'],
    'Age': [25, 30, 35],
    'City': ['Bangalore', 'Mumbai', 'Delhi']
}
#Your code here
df=pd.DataFrame(data)
#Display the first 2 rows of the data frame
#Your code here
print(df.loc[[0,1]])

#Print the age column
#Your code here
print(df["Age"])

#Filter rows where age is greater than 26
#Your code here
filtered_df=df[df["Age"]>26]

#Add a new column 'Country' with the value 'India' for all rows
#Your code here
df["Country"]="India"
print(df)
data1 = {
    'Name': ['Ramesh', 'Mahesh', 'Suresh'],
    'Age': [25, None, 35],
    'City': ['Bangalore', 'Mumbai', 'Delhi']
}

df2= pd.DataFrame(data1)

# Fill missing values in the 'Age' column with the mean age
#Your code here
df2['Age'].fillna(df2["Age"].mean(), inplace=True)
print(df2)

     Name  Age       City
0  Ramesh   25  Bangalore
1  Mahesh   30     Mumbai
0    25
1    30
2    35
Name: Age, dtype: int64
     Name  Age       City Country
0  Ramesh   25  Bangalore   India
1  Mahesh   30     Mumbai   India
2  Suresh   35      Delhi   India
     Name   Age       City
0  Ramesh  25.0  Bangalore
1  Mahesh  30.0     Mumbai
2  Suresh  35.0      Delhi


# Matplotlib Implementation

In [4]:
import matplotlib.pyplot as plt
import numpy as np



xpoints=np.array([1,2,3,4])
ypoints=np.array([2,4,6,8])

#Plot these points without drawing a line
#Your code here
#plt.scatter(xpoints,ypoints)


#Plotting with marker: Plot these points with a marker(Star marker)
#Your code here
#plt.plot(xpoints,ypoints,marker="*")

#Using fmt format, add circular marker,red color and Dashed line
#Your code here
plt.plot(xpoints,ypoints,'o--r')

#Add xlabel,ylabel and title for the plot.
#Your code here
plt.xlabel("hours")
plt.ylabel("workload")
plt.title("time management")

#Create a scatter plot for xpoints and ypoints
#Your code here



#Set color to the scatter plot. Blue,Green,Red and yellow color for each point respectively


ImportError: DLL load failed while importing _imaging: The specified module could not be found.

# Miscellaneous Modules Implementation

In [6]:
import random
import numpy as np

#Set the seed of random to 20
#Your code here
random.seed(20)

arr1=np.array([1,24,31,45,73,81,94,25])
a=list(arr1)

#Using the random module pick 4 different random numbers from arr1 and return their sum.
#Your code here

b=random.sample(a,4)
print(b)

[31, 25, 81, 1]
